# Generated by Django 5.0.2 on 2024-10-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
