# Generated by Django 5.0.2 on 2024-12-25 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_remove_customer_name'),
        ('handcrafts', '0002_alter_handcraft_handcraft_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.FloatField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('handcraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handcrafts.handcraft')),
            ],
        ),
    ]
