# Generated by Django 5.0.2 on 2025-03-14 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
        ('handcrafts', '0003_handcraft_handcraft_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountHandcraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discount.discount')),
                ('handcraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handcrafts.handcraft')),
            ],
        ),
    ]
