# Generated by Django 5.0.2 on 2025-03-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_discounthandcraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
