# Generated by Django 5.0.2 on 2024-12-24 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('maker', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handcraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handcraft_name', models.CharField(max_length=255)),
                ('handcraft_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('handcraft_count', models.IntegerField(max_length=10)),
                ('handcraft_image', models.ImageField(upload_to='handcraft_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.category')),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maker.maker')),
            ],
        ),
    ]
