# Generated by Django 5.0.2 on 2025-01-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handcrafts', '0002_alter_handcraft_handcraft_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='handcraft',
            name='handcraft_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
