# Generated by Django 5.0.2 on 2025-03-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handcrafts', '0003_handcraft_handcraft_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handcraft',
            name='handcraft_cost',
        ),
    ]
