# Generated by Django 5.0.2 on 2025-03-10 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_makerauction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionhandcraft',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.auction'),
        ),
    ]
