# Generated by Django 5.0.2 on 2024-10-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_description', models.TextField(default='', max_length=1000)),
                ('categorye_image', models.ImageField(upload_to='categories_images/')),
            ],
        ),
    ]
