# Generated by Django 5.0.2 on 2025-05-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='allow_simulation',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
