# Generated by Django 5.0.2 on 2024-12-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
