# Generated by Django 5.0.2 on 2025-01-14 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_remove_customer_name'),
        ('handcrafts', '0002_alter_handcraft_handcraft_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_price', models.IntegerField()),
                ('date_of_order', models.DateField()),
                ('time_of_order', models.TimeField()),
                ('delivery', models.BooleanField(default=True)),
                ('cost_for_pice', models.IntegerField(blank=True, default=0, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHandcraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('handcraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='handcrafts.handcraft')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderhandcrafts', to='order.order')),
            ],
        ),
    ]
