# Generated by Django 5.0.2 on 2025-01-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost_for_pice',
        ),
        migrations.AddField(
            model_name='order',
            name='full_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderhandcraft',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
