# Generated by Django 5.0.2 on 2025-03-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_cost_for_pice_order_full_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='full_cost',
        ),
    ]
